server:
  port: 8080

#logging:
#  level:
#    org.springframework: DEBUG

#[RESTful Service ?? ??] ??? ??
spring:
  messages:
    basename: messages
  #[Spring Boot API 사용] Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
